version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/spm
      - JWT_SECRET=change_me
      - CLIENT_URL=http://localhost:5173
      - STRIPE_SECRET_KEY=sk_test_xxx
      - STRIPE_WEBHOOK_SECRET=
      - AUTO_INVOICES_ENABLED=true
      - AUTO_INVOICES_CRON=0 0 1 * *
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    volumes:
      - agreements_data:/app/agreements
      - uploads_data:/app/uploads

  client:
    build: ./client
    environment:
      - VITE_API_URL=http://localhost:4000/api
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo_data:
  agreements_data:
  uploads_data:


